name: Progress Update

on:
  schedule:
    - cron: "37 14 * * *"  # Runs daily at a random time (2:37 PM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "Auto Updater"
          git config --global user.email "auto-updater@users.noreply.github.com"

      - name: Update progress log
        run: |
          FILE="progress_log.txt"
          if [[ ! -f "$FILE" ]]; then
            echo "Creating progress log..." > "$FILE"
          fi

          RANDOM_UPDATE=("Refactored a function" "Improved performance" "Updated documentation" "Fixed minor bug" "Reviewed code structure")
          MESSAGE=${RANDOM_UPDATE[$RANDOM % ${#RANDOM_UPDATE[@]}]}
          
          echo "$(date): $MESSAGE" >> "$FILE"

          git add "$FILE"
          git commit -m "$MESSAGE"
          git push
